version: '3.1'
services:
  postgres-db:
    image: postgres:16.4
    container_name: postgres
    networks:
      - nano-link-network
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 10s
      timeout: 5s
      retries: 10

  nanoLink:
    image: gomezbc/nano-link:0.0.1-SNAPSHOT
    container_name: nanoLink
    networks:
      - nano-link-network
    ports:
      - "8080:8080"
    depends_on:
      postgres-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-db:5432/postgres"
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mysecretpassword

networks:
  nano-link-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local