spring:
  cassandra:
    port: 9042
    keyspace-name: nanolink_keyspace
    connection:
      connect-timeout: 10s
      init-query-timeout: 10s
    local-datacenter: datacenter1
    contact-points: localhost
    schema-action: create_if_not_exists
    username: cassandra
    password: cassandra