server:
  port: 8080
spring:
  profiles:
    active: aws
  application:
    name: "nanoLink"
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
    discovery:
      client:
        health-indicator:
          enabled: false
  cassandra:
    config: "keyspaces-application.conf"
    keyspace-name: "aws"
    schema-action: NONE


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}