# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Database
  licenses: Apache-2.0
  images: |
    - name: cassandra
      image: docker.io/bitnami/cassandra:4.1.4-debian-12-r5
    - name: cassandra-exporter
      image: docker.io/bitnami/cassandra-exporter:2.3.8-debian-12-r18
    - name: os-shell
      image: docker.io/bitnami/os-shell:12-debian-12-r17
apiVersion: v2
appVersion: 4.1.4
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Apache Cassandra is an open source distributed database management system designed to handle large amounts of data across many servers, providing high availability with no single point of failure.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/cassandra/img/cassandra-stack-220x234.png
keywords:
- cassandra
- database
- nosql
maintainers:
- name: VMware, Inc.
  url: https://github.com/bitnami/charts
name: cassandra
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/cassandra
version: 11.0.1
